"""empty message

Revision ID: 149e2ffc20f1
Revises: 2244dcbf6c4c
Create Date: 2020-08-30 02:56:56.379221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '149e2ffc20f1'
down_revision = '2244dcbf6c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_datetime', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('news_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_type'], ['tbl_newstype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pub_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('news_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['news_type'], ['tbl_newstype.id'], name='news_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbl_news')
    # ### end Alembic commands ###
