"""empty message

Revision ID: 2244dcbf6c4c
Revises: d93dcca5bcb1
Create Date: 2020-08-30 02:56:35.109557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2244dcbf6c4c'
down_revision = 'd93dcca5bcb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_newstype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_datetime', sa.DateTime(), nullable=True),
    sa.Column('type_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_datetime', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('news_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_type'], ['tbl_newstype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('tbl_newstype')
    # ### end Alembic commands ###
