"""empty message

Revision ID: 98d0b31f0ffc
Revises: 43012a078d2c
Create Date: 2020-08-26 23:06:15.896484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d0b31f0ffc'
down_revision = '43012a078d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('phone', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'tbl_user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_user', type_='unique')
    op.drop_column('tbl_user', 'phone')
    # ### end Alembic commands ###
