"""empty message

Revision ID: debbdbd5288f
Revises: 826a7be00ef2
Create Date: 2020-08-27 12:56:54.765961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debbdbd5288f'
down_revision = '826a7be00ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('isDelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user', 'isDelete')
    # ### end Alembic commands ###
