"""empty message

Revision ID: 84184bc5b98b
Revises: cbb59fa1591d
Create Date: 2020-08-29 17:07:29.019844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84184bc5b98b'
down_revision = 'cbb59fa1591d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid'], ['tbl_user.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['tbl_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_friends')
    # ### end Alembic commands ###
