"""empty message

Revision ID: 4bc25de25ef4
Revises: 
Create Date: 2020-08-30 17:16:39.027059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc25de25ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('province', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('confirm', sa.Integer(), nullable=True),
    sa.Column('confirm_add', sa.Integer(), nullable=True),
    sa.Column('heal', sa.Integer(), nullable=True),
    sa.Column('dead', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ds', sa.DateTime(), nullable=True),
    sa.Column('confirm', sa.Integer(), nullable=True),
    sa.Column('confirm_add', sa.Integer(), nullable=True),
    sa.Column('suspect', sa.Integer(), nullable=True),
    sa.Column('suspect_add', sa.Integer(), nullable=True),
    sa.Column('heal', sa.Integer(), nullable=True),
    sa.Column('dead', sa.Integer(), nullable=True),
    sa.Column('dead_add', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_hotsearch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_hotsearch')
    op.drop_table('tbl_history')
    op.drop_table('tbl_details')
    # ### end Alembic commands ###
