"""empty message

Revision ID: 6b9ebf98fe82
Revises: 4bc25de25ef4
Create Date: 2020-08-30 17:26:15.336848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b9ebf98fe82'
down_revision = '4bc25de25ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_details', sa.Column('state', sa.String(length=16), nullable=True))
    op.drop_column('tbl_details', 'province')
    op.drop_column('tbl_details', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_details', sa.Column('city', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('tbl_details', sa.Column('province', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('tbl_details', 'state')
    # ### end Alembic commands ###
