"""empty message

Revision ID: 973bf02d7d0e
Revises: 6b9ebf98fe82
Create Date: 2020-08-30 17:37:05.345083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973bf02d7d0e'
down_revision = '6b9ebf98fe82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('confirm', sa.Integer(), nullable=True),
    sa.Column('confirm_add', sa.Integer(), nullable=True),
    sa.Column('heal', sa.Integer(), nullable=True),
    sa.Column('dead', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_details')
    # ### end Alembic commands ###
